id: ingress-nginx-valid-admission

info:
  name: Kubernetes Ingress Nginx Valid AdmissionReview 检测
  author: burso
  severity: high
  description: |
    检测到 Kubernetes Ingress Nginx Valid AdmissionReview 检测。目标响应或文件中可能暴露配置、凭据、密钥、令牌、环境变量或历史记录等敏感信息，可能被用于进一步入侵。
  metadata:
    verified: true
    max-request: 1
    shodan-query: ssl:"ingress-nginx" port:8443
  tags: tech,kubernetes,ingress,nginx,k8s,vuln

variables:
  string: "{{to_lower(rand_base(5))}}"

http:
  - raw:
      - |
        POST /validate HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {
          "kind": "AdmissionReview",
          "apiVersion": "admission.k8s.io/v1",
          "request": {
            "uid": "{{string}}",
            "kind": {
              "group": "networking.k8s.io",
              "version": "v1",
              "kind": "Ingress"
            },
            "operation": "CREATE",
            "object": {
              "metadata": {
                "name": "test-{{string}}",
                "namespace": "default"
              },
              "spec": {
                "rules": [
                  {
                    "host": "example.com",
                    "http": {
                      "paths": []
                    }
                  }
                ]
              }
            }
          }
        }

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(content_type, "application/json")'
          - 'contains_all(body, "AdmissionReview", "test-{{string}}")'
        condition: and
