id: postgresql-cluster-config

info:
  name: PostgreSQL 集群 配置
  author: DhiyaneshDk
  severity: high
  description: |
    检测到 PostgreSQL 集群 配置。目标功能在未认证状态下可访问，可能暴露管理入口、业务数据、系统状态或可执行操作，需确认是否存在访问控制缺失。
  classification:
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"postmaster_start_time"
  tags: postgresql,misconfig,unauth,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config"

    matchers:
      - type: dsl
        dsl:
          - 'contains_all(body, "postgresql","loop_wait")'
          - 'status_code == 200'
        condition: and
# digest: 4a0a0047304502200f12d9d304bd4fff4c5b6f4bc071384af1064317f072ed7b3ef6356e13fdab42022100871c78556fa96cf323501f47123c514adac1d4a87e56cece5f670ba6e952b105:922c64590222798bb761d5b6d8e72950