id: awstats-config

info:
  name: AWStats 配置检测（暴露面识别）
  author: sheikhrishad
  severity: info
  description: 检测到对外可访问的 AWStats 配置。这类配置资源可能包含部署细节、访问凭据、内部地址、组件版本或调试开关，公开暴露后会显著增加被侦察和后续利用的风险。
  reference:
    - https://www.awstats.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure,awstats,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/awstats/"
      - "{{BaseURL}}/awstats.conf"

    matchers:
      - type: word
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and
# digest: 4a0a00473045022044622fb43e8801b567758bf29570dd4e48b47edbcbc2964806c84658e7366e01022100ba7827efa79e5f69fcbf49622c41c81ea71abeec77d64d1e6740cf30c1f86625:922c64590222798bb761d5b6d8e72950