id: dockerfile-hidden-disclosure

info:
  name: Dockerfile 检测（暴露面识别）
  author: dhiyaneshDk
  severity: medium
  description: 检测到对外可访问的 Dockerfile。这类配置资源可能包含部署细节、访问凭据、内部地址、组件版本或调试开关，公开暴露后会显著增加被侦察和后续利用的风险。
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-552
  metadata:
    max-request: 3
  tags: exposure,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.dockerfile"
      - "{{BaseURL}}/.Dockerfile"
      - "{{BaseURL}}/Dockerfile"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+'
        part: body

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/html"
        negative: true
# digest: 4b0a00483046022100d179462f21b992a9c0d30b03b74c08de0446097b68015ef3811dabe2747471dc022100b87d4751722e876ac16753a3cc179d0d8fe267c2757ec6c71bd00fc8130f50f6:922c64590222798bb761d5b6d8e72950