id: exposed-darcs

info:
  name: Darcs 配置检测（暴露面识别）
  author: daffainfo
  severity: info
  description: 检测到对外可访问的 Darcs 配置。这类配置资源可能包含部署细节、访问凭据、内部地址、组件版本或调试开关，公开暴露后会显著增加被侦察和后续利用的风险。
  reference:
    - http://darcs.net/Using/Configuration#sources
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/_darcs/prefs/binaries"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Binary file regexps"

      - type: status
        status:
          - 200
# digest: 4a0a004730450220378ec2f4e810587e2890d3b8720a30dcea66dd156040c0fb3b64d71ef85aef67022100aec2e3c894d95401bf054540f55c23f6c0b0a7574c455cf5526a1762749bdeb9:922c64590222798bb761d5b6d8e72950