id: gitlab-ci-yml

info:
  name: GitLab CI YAML 文件暴露（暴露面识别）
  author: DhiyaneshDK
  severity: medium
  description: |
    检测到对外可访问的 GitLab CI YAML 文件。相关文件可能泄露项目结构、依赖关系、部署细节、敏感参数或其他不应公开的内部信息。
  impact: |
    - 暴露的资源可能泄露敏感配置、内部实现细节或历史数据。
    - 攻击者可结合这些信息开展进一步侦察、未授权访问或定向利用。
  reference:
    - https://x.com/RootMoksha/status/1816571625388818923/photo/1
  classification:
    cpe: cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: gitlab
    product: gitlab
    shodan-query: html:"gitlab-ci.yml"
  tags: exposure,config,cicd,gitlab,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.gitlab-ci.yml"
      - "{{BaseURL}}/gitlab-ci.yml"
      - "{{BaseURL}}/.gitlab-ci/variables.yml"

    stop-at-first-match: true

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "variables:"
          - "before_script:"
        condition: and

      - type: word
        part: body
        words:
          - "stage: build"
          - "script:"
          - "image:"
        condition: and

      - type: word
        part: body
        words:
          - "variables:"
          - "releasePath:"
          - "sshUser:"
        condition: and
# digest: 4a0a00473045022100c877bd4fb88365607b2966eb9742a2aac22dff1a851dab47090c4c7c31be4edd02207d445bfa36816c2fb91dd975b72cf9cf14d5887a5ee20576b14c0604cb3d0f1c:922c64590222798bb761d5b6d8e72950