id: kubernetes-k8s-kube-api-version

info:
  name: Kubernetes API Version 指纹识别（指纹识别）
  author: sharath,raesene
  severity: info
  description: >-
    Kubernetes API Server 是集群控制面的核心接口，版本接口用于返回集群 API 版本与服务端构建信息。该模板通过请求目标服务并检查预设路径或首页响应、页面正文关键字、状态码等指纹特征，判断目标是否使用或暴露了
    Kubernetes API Version 相关组件；命中结果仅表示指纹特征匹配，可用于资产盘点、技术栈识别和后续安全评估，不代表已确认存在可利用漏洞。
  metadata:
    max-request: 1
  tags: tech,kubernetes,devops,kube,discovery
http:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"major":'
          - '"minor":'
          - '"goVersion":'
        condition: and

    extractors:
      - type: json
        json:
          - ".gitVersion"
# digest: 490a00463044022049b6d4cec1b8757345e67d32d05b38515f497909180953e6136c0dc28d76555202200ad48689004d28291f3399b346f4128eccb62a32b854d63457ba4e28b14c8c89:922c64590222798bb761d5b6d8e72950