id: crowdin

info:
  name: Crowdin 用户名信息枚举（OSINT）
  author: dwisiswant0
  severity: info
  description: |
    对 Crowdin 的用户名进行 OSINT 枚举检查。模板请求公开路径 https://crowdin.com/profile/用户名，当响应状态为 200 且页面或响应内容命中 “) – Crowdin” 等用户资料页特征时，判定目标用户名可能存在。
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,osint-hobby,crowdin,discovery

self-contained: true

http:
  - method: GET
    path:
      - "https://crowdin.com/profile/{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - ") – Crowdin"
# digest: 4b0a00483046022100eea6155ea03fddb6ae5bb953275ab5c141823cf97f678dcb0adfef439168e792022100a7fa33d741fe4f17f51931dd4b08122c22e2ded070767de68c147aaccc3d2782:922c64590222798bb761d5b6d8e72950