id: producthunt

info:
  name: Producthunt 用户名信息枚举（OSINT）
  author: dwisiswant0
  severity: info
  description: |
    Producthunt 是面向商业展示、职业资料、客户沟通或业务协作的在线平台，用户资料页通常会公开展示个人名片、作品、服务或组织相关信息。该模板用于在公开互联网侧枚举 Producthunt 用户名，不需要认证；模板请求公开路径 https://www.producthunt.com/@用户名，并结合响应状态为 200、页面或响应内容命中 “s profile on Product Hunt” 等资料页特征判断目标用户名是否存在。该检查属于 OSINT 用户枚举，结果仅表示公开资料页或公开搜索结果可被访问，不代表目标平台存在可直接修复的漏洞。
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,osint-business,producthunt,discovery

self-contained: true

http:
  - method: GET
    path:
      - "https://www.producthunt.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "s profile on Product Hunt"
# digest: 490a0046304402206e75053d2ba911c4b0785bdaddd054b007ea5f71d73f986d81427e6847da213d02201fac559ce38f432fb68ff753490c20296b30f9b1fe5946596998fb3b15be0ea0:922c64590222798bb761d5b6d8e72950